Modified for 0.11.

diff --git a/Installer/Install_resources/InstallationCheck b/Installer/Install_resources/InstallationCheck
--- a/Installer/Install_resources/InstallationCheck
+++ b/Installer/Install_resources/InstallationCheck
@@ -29,13 +29,28 @@ then
 fi
 echo "Darwin version `$sysctl -n kern.osrelease` detected."
 
+echo "Checking for other alternative trackpad drivers..."
+if kextstat | grep com.ragingmenace.driver.SideTrack > /dev/null
+then
+    echo "ERROR: SideTrack seems to be installed on your machine."
+    echo "iScroll2 is not compatible with SideTrack."
+    exit $[(3<<5)+17]
+fi
+if kextstat | grep uk.org.outpost.driver.OutpostADBMouse > /dev/null
+then
+    echo "ERROR: FingaMIDI seems to be installed on your machine."
+    echo "iScroll2 is not compatible with FingaMIDI."
+    exit $[(3<<5)+18]
+fi
+echo "No other known alternative drivers detected."
+
 echo "Checking if trackpad driver is loaded..."
 if ! ($kextstat | grep com.apple.driver.AppleADBMouse > /dev/null || \
     $kextstat | grep name.razzfazz.iScroll2 > /dev/null || \
     $kextstat | grep name.razzfazz.driver.iScroll2 > /dev/null)
 then 
     echo "ERROR: No compatible trackpad driver loaded!"
-    exit $[(3<<5)+17]
+    exit $[(3<<5)+19]
 fi
 echo "Apple trackpad driver is loaded."
 
@@ -43,7 +58,7 @@ echo "Checking if trackpad supports W-Enhanced mode..."
 if ! $ioreg -n AppleADBMouseType4 | grep "W Enhanced Trackpad" > /dev/null
 then
     echo "ERROR: Trackpad does not seem to support W-Enhanced mode."
-    exit $[(3<<5)+18]
+    exit $[(3<<5)+20]
 fi
 echo "Trackpad seems to support W-Enhanced mode."
 
