Fixed InstallationCheck script to work for upgrades.

diff --git a/Installer/Install_resources/InstallationCheck b/Installer/Install_resources/InstallationCheck
--- a/Installer/Install_resources/InstallationCheck
+++ b/Installer/Install_resources/InstallationCheck
@@ -7,10 +7,11 @@ then
     exit $[(3<<5)+16]
 fi
 echo "Darwin version `sysctl -n kern.osrelease` detected."
-echo "Checking if Apple trackpad driver is loaded..."
-if ! kextstat | grep com.apple.driver.AppleADBMouse > /dev/null
+echo "Checking if trackpad driver is loaded..."
+if ! (kextstat | grep com.apple.driver.AppleADBMouse > /dev/null || \
+    kextstat | grep name.razzfazz.iScroll > /dev/null)
 then 
-    echo "ERROR: Apple trackpad driver not loaded!"
+    echo "ERROR: No compatible trackpad driver loaded!"
     exit $[(3<<5)+17]
 fi
 echo "Apple trackpad driver is loaded."
